#  server is the main entry point, which will serve the application and forward requests to the php interpreter container
#  php interpreter will indirectly talk to mysql database

version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - '3000:9000'
  mysql:
    image: 'mysql:5.7'
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./env/mysql.env
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm: